spring:
  application:
    name: fisherman
  config:
    import:
      - optional:file:.env[.properties]
  profiles:
    include:
      - datasource
      - security
      - redis
      - mail
      - redis
      - jwt
springdoc:
  use-fqn: true
